version: '3'

services:
  postgres:
    image: postgres
    container_name: url-shortener-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: url_shortener
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d url_shortener']
      interval: 1s
      timeout: 10s
      retries: 10